project:
  type: website
  output-dir: docs

website:
  title: "Carlo Broderick"
  navbar:
  # these are the pages on the nav bar, they refer to the .qmd files in the directory
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - about2.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: mystyles.scss
    toc: true

editor: visual
