project:
  type: website
  output-dir: docs

website:
  title: "carlobroderick.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: mystyles.scss
    toc: true

editor: visual
